name: "CI"
on:
  push:
    branches:
      - main
      - ci/**
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/**
      - home/**
  pull_request:
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/**
      - home/**

jobs:
  build:
    # Map Nix system names to GitHub runners
    runs-on: ${{
      matrix.system == 'aarch64-darwin' && 'macos-14' ||
      matrix.system == 'x86_64-darwin' && 'macos-latest' ||
      matrix.system == 'x86_64-linux' && 'ubuntu-latest' }}
    timeout-minutes: 60 # Prevent infinite runs

    strategy:
      matrix:
        system:
          - aarch64-darwin
          - x86_64-darwin
          - x86_64-linux
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org https://cache.garnix.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Install om using nix
        run: nix --accept-flake-config profile install github:juspay/omnix

      - name: Run om show
        run: om show .

      - name: Run om ci
        run: |
          om ci \
            --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" \
            run \
            --systems "${{ matrix.system }}"

      - name: Run om tests
        run: om init --test .

  create-tag:
    needs: build
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push tag
        run: |
          TAG="release-$(date +'%Y%m%d')-${GITHUB_SHA::7}"
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git tag -a "$TAG" -m "Automated release tag"
          git push origin "$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
