name: Build

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci/**
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/**
      - home/**
  pull_request:
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/**
      - home/**

jobs:
  build:
    # Map Nix system names to GitHub runners
    runs-on: ${{
      matrix.system == 'aarch64-darwin' && 'macos-14' ||
      matrix.system == 'x86_64-linux' && 'ubuntu-latest' }}
    timeout-minutes: 60 # Prevent infinite runs

    strategy:
      matrix:
        system:
          - aarch64-darwin
          - x86_64-linux
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@3c90616f6a336746c4d0950d1e635b9a0ce1569c # v3
        with:
          host: github.com
          private-key: ${{ secrets.NIX_SECRETS_SSH }}

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org https://cache.garnix.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Install om using nix
        run: nix --accept-flake-config profile install github:juspay/omnix

      - name: Run om show
        run: om show .

      - name: Run om ci
        run: |
          om ci \
            run \
            --systems "${{ matrix.system }}"
