name: Add new issues to GitHub Project
on:
  issues:
    types: [opened]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        run: |
          gh api graphql -F projectId='PVT_kwHO12345' -F contentId='${{ github.event.issue.node_id }}' -f query='
          mutation($projectId: ID!, $contentId: ID!) {
            addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
              item {
                id
              }
            }
          }'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
