name: Add new issues to GitHub Project
on:
  issues:
    types: [opened]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: "https://github.com/orgs/jaimemachadoneto/projects/2"
          github-token: ${{ secrets.GITHUB_TOKEN }}
