name: Add Issues to GitHub Project

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add issue to project
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.MY_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"project_id": "2", "content_id": "${{ github.event.issue.node_id }}"}' \
          https://api.github.com/graphql
